version: "3.2"
services:
  app:
    build: .
    ports:
      - "1323:1323"
    depends_on:
      - redis
    command: "library-inventory"
    environment:
      - DELAY=5
  redis:
    image: "redis"
    ports: 
      - "6379:6379"